Convert state from live data to flow. Fix UILazyColumn

diff --git a/scripts/hooks/commit-msg b/scripts/hooks/commit-msg
--- a/scripts/hooks/commit-msg
+++ b/scripts/hooks/commit-msg
@@ -12,8 +12,14 @@ if [ "$status" = 0 ] ; then
 else
   echo "Static analysis failed. Formatting with ktlint."
   ./gradlew ktlintFormat
-  commitMessage=$(cat $1)
-  git add .
-  git commit -m "$commitMessage" --no-verify
-  exit 0
+
+  newStatus=$?
+  if ["$newStatus" = 0] ; then
+    commitMessage=$(cat $1)
+    git add .
+    git commit -m "$commitMessage" --no-verify
+    exit 0
+  else
+    echo "Formatting failed."
+    exit 1
 fi
